=== fiesta-framework/ARFiesta/app/Local/languages_config.dtd
<!ELEMENT languages_config (meta,accepted_languages)>
<!ELEMENT meta (creation,update*)>
<!ELEMENT accepted_languages (language*)> 
<!ELEMENT language (translation*)>
<!ELEMENT translation EMPTY>

<!ATTLIST languages_config target_application CDATA #REQUIRED>

<!ATTLIST creation author CDATA #IMPLIED>
<!ATTLIST creation date CDATA #IMPLIED>
<!ATTLIST creation comment CDATA #IMPLIED>

<!ATTLIST update author CDATA #IMPLIED>
<!ATTLIST update date CDATA #IMPLIED>
<!ATTLIST update comment CDATA #IMPLIED>

<!ATTLIST language id ID #REQUIRED>
<!ATTLIST language is_default (true|false) #IMPLIED>
<!ATTLIST language is_alias (true|false) #IMPLIED>
<!ATTLIST language alias_idref IDREF #IMPLIED>
<!ATTLIST language comment CDATA #IMPLIED>

<!ATTLIST translation translated_idref IDREF #REQUIRED>
<!ATTLIST translation translation CDATA #REQUIRED>

=== fiesta-framework/ARFiesta/app/Local/languages_config.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE languages_config SYSTEM "languages_config.dtd">
<languages_config target_application="php-login-lang">
	<meta> 
	<creation author="Tristan Vanrullen" date="09/12/2013"/>
	<update author="Tristan Vanrullen" date="09/12/2013" comment="added aliases for browser language names"/>
	</meta>
	<accepted_languages>
		<language id="fr_FR">
			<translation translated_idref="fr_FR" translation="FranÃ§ais"/>
			<translation translated_idref="en_UK" translation="French"/>
		</language>
		<language id="en_UK" is_default="true">
			<translation translated_idref="fr_FR" translation="Anglais"/>
			<translation translated_idref="en_UK" translation="English"/>
		</language>
		<language id="en" alias_idref="en_UK" is_alias="true"/>
		<language id="fr" alias_idref="fr_FR" is_alias="true"/>
	</accepted_languages>
</languages_config>
